package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
	"unicode"
)

var httpClient = &http.Client{Timeout: 30 * time.Second}

var version = "dev"

const (
	ttsDir       = "assets/tts"
	bgmDir       = "assets/bg-music"
	outputDir    = "_output"
	defaultVoice = "hpp4J3VqNfWAUOO0d1Us"
)

var audioExts = []string{".mp3", ".wav", ".m4a"}

// ── Config ────────────────────────────────────────────────────────────────────

type Config struct {
	ElevenLabsAPIKey  string `json:"elevenlabs_api_key"`
	ElevenLabsVoiceID string `json:"elevenlabs_voice_id"`
}

func configDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "astra-carplay-music")
}

func configFile() string {
	return filepath.Join(configDir(), "config.json")
}

func loadConfig() Config {
	data, err := os.ReadFile(configFile())
	if err != nil {
		return Config{}
	}
	var cfg Config
	_ = json.Unmarshal(data, &cfg)
	return cfg
}

func saveConfig(cfg Config) error {
	if err := os.MkdirAll(configDir(), 0700); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(configFile(), data, 0600)
}

// ── init subcommand ───────────────────────────────────────────────────────────

func cmdInit(args []string) {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: astra-carplay-music init\n\n")
		fmt.Fprintf(os.Stderr, "Create project folder structure and a sample scripts.txt.\n\n")
		fmt.Fprintf(os.Stderr, "Creates:\n")
		fmt.Fprintf(os.Stderr, "  %s/       TTS audio files generated by ElevenLabs\n", ttsDir)
		fmt.Fprintf(os.Stderr, "  %s/  Background music files (.mp3/.wav/.m4a)\n", bgmDir)
		fmt.Fprintf(os.Stderr, "  %s/        Mixed output files\n", outputDir)
		fmt.Fprintf(os.Stderr, "  scripts.txt          List of texts to generate as TTS\n")
	}
	_ = fs.Parse(args)

	dirs := []string{ttsDir, bgmDir, outputDir}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: cannot create '%s': %s\n", d, err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "  ✓ %s/\n", d)
	}

	const sampleScripts = "# Each non-empty line will be generated as a separate TTS audio file.\n# Lines starting with # are comments and will be skipped.\n\nWelcome to your destination\n"
	scriptPath := "scripts.txt"
	if _, err := os.Stat(scriptPath); os.IsNotExist(err) {
		if err := os.WriteFile(scriptPath, []byte(sampleScripts), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: cannot create scripts.txt: %s\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "  ✓ scripts.txt  (sample)\n")
	} else {
		fmt.Fprintf(os.Stderr, "  ~ scripts.txt  (already exists, skipped)\n")
	}

	fmt.Fprintf(os.Stderr, "\nProject ready. Next steps:\n\n")
	fmt.Fprintf(os.Stderr, "  1. Set your ElevenLabs API key:\n")
	fmt.Fprintf(os.Stderr, "       astra-carplay-music setup --api-key <key>\n\n")
	fmt.Fprintf(os.Stderr, "  2. Drop background music files into %s/  (.mp3 / .wav / .m4a)\n\n", bgmDir)
	fmt.Fprintf(os.Stderr, "  3. Edit scripts.txt — one line per TTS clip\n\n")
	fmt.Fprintf(os.Stderr, "  4. Generate TTS audio:\n")
	fmt.Fprintf(os.Stderr, "       astra-carplay-music tts --file scripts.txt\n\n")
	fmt.Fprintf(os.Stderr, "  5. Mix all TTS × BG combinations:\n")
	fmt.Fprintf(os.Stderr, "       astra-carplay-music --duration 7 --fade-out 1.5\n\n")
	fmt.Fprintf(os.Stderr, "  Output files will be in %s/\n", outputDir)
}

// ── setup subcommand ──────────────────────────────────────────────────────────

func cmdSetup(args []string) {
	fs := flag.NewFlagSet("setup", flag.ExitOnError)
	apiKey  := fs.String("api-key", "", "ElevenLabs API key")
	voiceID := fs.String("voice-id", "", "ElevenLabs Voice ID")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: astra-carplay-music setup [options]\n\n")
		fmt.Fprintf(os.Stderr, "Save ElevenLabs credentials to %s\n\n", configFile())
		fmt.Fprintf(os.Stderr, "Run without flags to show current config.\n\n")
		fmt.Fprintf(os.Stderr, "Examples:\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music setup --api-key sk_...\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music setup --voice-id abc123\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music setup\n\n")
		fmt.Fprintf(os.Stderr, "Options:\n")
		fs.PrintDefaults()
	}
	_ = fs.Parse(args)

	cfg := loadConfig()

	if *apiKey == "" && *voiceID == "" {
		fmt.Fprintf(os.Stderr, "Config: %s\n\n", configFile())
		if cfg.ElevenLabsAPIKey != "" {
			k := cfg.ElevenLabsAPIKey
			masked := k[:min(4, len(k))] + "****"
			fmt.Fprintf(os.Stderr, "  api-key  : %s\n", masked)
		} else {
			fmt.Fprintf(os.Stderr, "  api-key  : (not set)\n")
		}
		v := cfg.ElevenLabsVoiceID
		if v == "" {
			v = fmt.Sprintf("(default: %s)", defaultVoice)
		}
		fmt.Fprintf(os.Stderr, "  voice-id : %s\n\n", v)
		fmt.Fprintf(os.Stderr, "Use --api-key and --voice-id to update.\n")
		return
	}

	if *apiKey != "" {
		cfg.ElevenLabsAPIKey = *apiKey
		fmt.Fprintf(os.Stderr, "Warning: API key passed via flag may be saved in your shell history.\n")
		fmt.Fprintf(os.Stderr, "         Consider running: history -d $(history 1) to remove it.\n\n")
	}
	if *voiceID != "" {
		cfg.ElevenLabsVoiceID = *voiceID
	}
	if err := saveConfig(cfg); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "✓ Config saved: %s\n", configFile())
}

// ── tts subcommand ────────────────────────────────────────────────────────────

func slugify(text string) string {
	text = strings.ToLower(strings.TrimSpace(text))
	var b strings.Builder
	prevDash := false
	for _, r := range text {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			prevDash = false
		} else if !prevDash {
			b.WriteRune('-')
			prevDash = true
		}
	}
	s := strings.Trim(b.String(), "-")
	if len(s) > 60 {
		s = s[:60]
	}
	return s
}

func generateTTS(text, voiceID, apiKey, outPath string, speed float64) error {
	payload, _ := json.Marshal(map[string]any{
		"text": text,
		"voice_settings": map[string]any{
			"speed": speed,
		},
	})
	url := fmt.Sprintf("https://api.elevenlabs.io/v1/text-to-speech/%s", voiceID)

	req, err := http.NewRequest("POST", url, bytes.NewReader(payload))
	if err != nil {
		return err
	}
	req.Header.Set("xi-api-key", apiKey)
	req.Header.Set("Content-Type", "application/json")

	resp, err := httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("API %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = io.Copy(f, resp.Body)
	return err
}

func cmdTTS(args []string) {
	fs := flag.NewFlagSet("tts", flag.ExitOnError)
	text    := fs.String("text", "", "Text to generate as TTS audio")
	file    := fs.String("file", "", "Text file — one line per clip, lines starting with # are skipped")
	voiceID := fs.String("voice-id", "", "ElevenLabs Voice ID (overrides config)")
	speed   := fs.Float64("speed", 0.9, "Speech speed: 0.7 (slow) to 1.2 (fast) (default: 0.9)")
	outDir  := fs.String("output-dir", ttsDir, "Directory to save generated TTS files")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: astra-carplay-music tts [options]\n\n")
		fmt.Fprintf(os.Stderr, "Generate TTS audio via ElevenLabs API and save to %s/\n\n", ttsDir)
		fmt.Fprintf(os.Stderr, "Requires an API key — run setup first:\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music setup --api-key <key>\n\n")
		fmt.Fprintf(os.Stderr, "Output filename format: {text-slug}_{voice-id}.mp3\n\n")
		fmt.Fprintf(os.Stderr, "Examples:\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music tts --text \"Welcome to BMW\"\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music tts --file scripts.txt\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music tts --file scripts.txt --speed 1.1 --voice-id abc123\n\n")
		fmt.Fprintf(os.Stderr, "Options:\n")
		fs.PrintDefaults()
	}
	_ = fs.Parse(args)

	cfg := loadConfig()

	if *speed < 0.7 || *speed > 1.2 {
		fmt.Fprintln(os.Stderr, "Error: --speed must be between 0.7 and 1.2")
		os.Exit(2)
	}

	if cfg.ElevenLabsAPIKey == "" {
		fmt.Fprintln(os.Stderr, "Error: ElevenLabs API key not set.")
		fmt.Fprintln(os.Stderr, "Run: astra-carplay-music setup --api-key <key>")
		os.Exit(2)
	}

	voice := cfg.ElevenLabsVoiceID
	if voice == "" {
		voice = defaultVoice
	}
	if *voiceID != "" {
		voice = *voiceID
	}

	var lines []string
	switch {
	case *text != "":
		lines = []string{*text}
	case *file != "":
		f, err := os.Open(*file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: cannot open '%s': %s\n", *file, err)
			os.Exit(1)
		}
		defer f.Close()
		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line != "" && !strings.HasPrefix(line, "#") {
				lines = append(lines, line)
			}
		}
	default:
		fs.Usage()
		os.Exit(2)
	}

	if len(lines) == 0 {
		fmt.Fprintln(os.Stderr, "Error: no text lines found to generate.")
		os.Exit(2)
	}

	fmt.Fprintf(os.Stderr, "Generating %d TTS  [voice: %s | speed: %.2f]  →  %s/\n\n", len(lines), voice, *speed, *outDir)

	used := map[string]int{}
	ok, fail := 0, 0
	for _, line := range lines {
		slug := slugify(line)
		if slug == "" {
			slug = "tts"
		}
		idx := used[slug]
		used[slug]++

		name := fmt.Sprintf("%s_%s.mp3", slug, voice)
		if idx > 0 {
			name = fmt.Sprintf("%s_%s-%d.mp3", slug, voice, idx+1)
		}

		outPath := filepath.Join(*outDir, name)
		if err := generateTTS(line, voice, cfg.ElevenLabsAPIKey, outPath, *speed); err != nil {
			fmt.Fprintf(os.Stderr, "  ✗ %s: %s\n", name, err)
			fail++
			continue
		}
		fmt.Fprintf(os.Stderr, "  ✓ %s\n", name)
		ok++
	}

	fmt.Fprintf(os.Stderr, "\nDone. %d succeeded", ok)
	if fail > 0 {
		fmt.Fprintf(os.Stderr, ", %d failed", fail)
	}
	fmt.Fprintf(os.Stderr, "  →  %s/\n", *outDir)
	if fail > 0 {
		os.Exit(1)
	}
}

// ── reset subcommand ──────────────────────────────────────────────────────────

func cmdReset(args []string) {
	fs := flag.NewFlagSet("reset", flag.ExitOnError)
	force := fs.Bool("force", false, "Skip confirmation prompt")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: astra-carplay-music reset [--force]\n\n")
		fmt.Fprintf(os.Stderr, "Delete all generated TTS and output files to start fresh.\n")
		fmt.Fprintf(os.Stderr, "%s/ is preserved — it contains your background music.\n\n", bgmDir)
		fmt.Fprintf(os.Stderr, "Removes:\n")
		fmt.Fprintf(os.Stderr, "  %s/   generated TTS files\n", ttsDir)
		fmt.Fprintf(os.Stderr, "  %s/     mixed output files\n\n", outputDir)
		fmt.Fprintf(os.Stderr, "Keeps:\n")
		fmt.Fprintf(os.Stderr, "  %s/  background music (untouched)\n\n", bgmDir)
		fmt.Fprintf(os.Stderr, "Options:\n")
		fs.PrintDefaults()
	}
	_ = fs.Parse(args)

	if !*force {
		fmt.Fprintf(os.Stderr, "This will delete all files in %s/ and %s/\n", ttsDir, outputDir)
		fmt.Fprintf(os.Stderr, "Continue? [y/N] ")
		var answer string
		fmt.Scanln(&answer)
		if strings.ToLower(strings.TrimSpace(answer)) != "y" {
			fmt.Fprintln(os.Stderr, "Aborted.")
			os.Exit(0)
		}
	}

	fmt.Println()
	cleanDir(ttsDir)
	cleanDir(outputDir)
	fmt.Fprintf(os.Stderr, "\nReset done. Re-generate TTS with:\n")
	fmt.Fprintf(os.Stderr, "  astra-carplay-music tts --file scripts.txt\n")
}

// ── clean subcommand ──────────────────────────────────────────────────────────

func cleanDir(dir string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  skip %s/ (not found)\n", dir)
		return
	}
	count := 0
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		ext := strings.ToLower(filepath.Ext(e.Name()))
		for _, ae := range audioExts {
			if ext == ae {
				_ = os.Remove(filepath.Join(dir, e.Name()))
				count++
				break
			}
		}
	}
	fmt.Fprintf(os.Stderr, "  ✓ %s/  (%d file(s) removed)\n", dir, count)
}

func cmdClean(args []string) {
	fs := flag.NewFlagSet("clean", flag.ExitOnError)
	doTTS    := fs.Bool("tts", false, fmt.Sprintf("Remove audio files in %s/", ttsDir))
	doBG     := fs.Bool("bg", false, fmt.Sprintf("Remove audio files in %s/", bgmDir))
	doOutput := fs.Bool("output", false, fmt.Sprintf("Remove audio files in %s/", outputDir))
	force    := fs.Bool("force", false, "Skip confirmation prompt")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: astra-carplay-music clean [options]\n\n")
		fmt.Fprintf(os.Stderr, "Remove audio files from the specified directories.\n")
		fmt.Fprintf(os.Stderr, "No directory flag = clean all three directories.\n\n")
		fmt.Fprintf(os.Stderr, "Examples:\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music clean --force          # remove all, no prompt\n")
		fmt.Fprintf(os.Stderr, "  astra-carplay-music clean --tts            # only %s/\n", ttsDir)
		fmt.Fprintf(os.Stderr, "  astra-carplay-music clean --output         # only %s/\n", outputDir)
		fmt.Fprintf(os.Stderr, "  astra-carplay-music clean --tts --output --force\n\n")
		fmt.Fprintf(os.Stderr, "Options:\n")
		fs.PrintDefaults()
	}
	_ = fs.Parse(args)

	all := !*doTTS && !*doBG && !*doOutput

	var targets []string
	if *doTTS || all   { targets = append(targets, ttsDir) }
	if *doBG || all    { targets = append(targets, bgmDir) }
	if *doOutput || all { targets = append(targets, outputDir) }

	if !*force {
		fmt.Fprintf(os.Stderr, "This will delete all audio files in: %s\n", strings.Join(targets, ", "))
		fmt.Fprintf(os.Stderr, "Continue? [y/N] ")
		var answer string
		fmt.Scanln(&answer)
		if strings.ToLower(strings.TrimSpace(answer)) != "y" {
			fmt.Fprintln(os.Stderr, "Aborted.")
			os.Exit(0)
		}
	}

	fmt.Println()
	for _, t := range targets {
		cleanDir(t)
	}
	fmt.Println()
}

// ── mix (default) ─────────────────────────────────────────────────────────────

func findAudio(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("cannot read directory '%s': %w", dir, err)
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		ext := strings.ToLower(filepath.Ext(e.Name()))
		for _, ae := range audioExts {
			if ext == ae {
				files = append(files, filepath.Join(dir, e.Name()))
				break
			}
		}
	}
	return files, nil
}

func mix(ttsPath, bgPath, outPath string, bgmVolume, ttsVolume float64, delayMs int, duration, fadeOut float64) error {
	mixChain := "amix=inputs=2:duration=first:dropout_transition=0"
	if fadeOut > 0 && duration > 0 {
		fadeStart := duration - fadeOut
		mixChain += fmt.Sprintf(",afade=t=out:st=%.3f:d=%.3f", fadeStart, fadeOut)
	}
	filter := fmt.Sprintf(
		"[0]volume=%.1fdB[bg];[1]volume=%.1fdB,adelay=%d|%d[tts];[bg][tts]%s[out]",
		bgmVolume, ttsVolume, delayMs, delayMs, mixChain,
	)
	args := []string{"-y", "-i", bgPath, "-i", ttsPath, "-filter_complex", filter, "-map", "[out]", "-b:a", "320k"}
	if duration > 0 {
		args = append(args, "-t", fmt.Sprintf("%.3f", duration))
	}
	args = append(args, outPath)

	if out, err := exec.Command("ffmpeg", args...).CombinedOutput(); err != nil {
		return fmt.Errorf("ffmpeg error: %s", string(out))
	}
	return nil
}

func doctor() {
	type check struct {
		name, command string
		args          []string
		install       string
	}
	checks := []check{
		{"ffmpeg", "ffmpeg", []string{"-version"}, "brew install ffmpeg"},
	}

	ok := true
	for _, c := range checks {
		out, err := exec.Command(c.command, c.args...).Output()
		if err != nil {
			fmt.Printf("  ✗ %-10s not found  →  %s\n", c.name, c.install)
			ok = false
			continue
		}
		firstLine := strings.SplitN(strings.TrimSpace(string(out)), "\n", 2)[0]
		fmt.Printf("  ✓ %-10s %s\n", c.name, firstLine)
	}

	fmt.Println()
	if ok {
		fmt.Println("All dependencies OK. Tool is ready.")
	} else {
		fmt.Fprintln(os.Stderr, "Missing dependencies. Install them and run again.")
		os.Exit(1)
	}
}

func runMix(bgmVolume, ttsVolume float64, delayMs int, duration, fadeOut float64) error {
	for _, dir := range []string{ttsDir, bgmDir} {
		if _, err := os.Stat(dir); os.IsNotExist(err) {
			return fmt.Errorf("directory '%s' not found. Run 'astra-carplay-music init' first", dir)
		}
	}

	ttsFiles, err := findAudio(ttsDir)
	if err != nil {
		return err
	}
	bgFiles, err := findAudio(bgmDir)
	if err != nil {
		return err
	}

	if len(ttsFiles) == 0 {
		return fmt.Errorf("no audio files found in '%s/' — run 'tts' command first. Supported: .mp3, .wav, .m4a", ttsDir)
	}
	if len(bgFiles) == 0 {
		return fmt.Errorf("no audio files found in '%s/'. Add background music (.mp3, .wav, .m4a)", bgmDir)
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("cannot create output directory: %w", err)
	}

	total := len(ttsFiles) * len(bgFiles)
	durStr := "full"
	if duration > 0 {
		durStr = fmt.Sprintf("%.1fs", duration)
	}
	fadeStr := "none"
	if fadeOut > 0 {
		fadeStr = fmt.Sprintf("%.1fs", fadeOut)
	}
	fmt.Fprintf(os.Stderr, "%d TTS × %d BG = %d file(s)  [bgm %+.0fdB | tts %+.0fdB | delay %.1fs | duration %s | fadeout %s]\n\n",
		len(ttsFiles), len(bgFiles), total, bgmVolume, ttsVolume, float64(delayMs)/1000, durStr, fadeStr)

	for _, bg := range bgFiles {
		bgName := strings.TrimSuffix(filepath.Base(bg), filepath.Ext(bg))
		for _, tts := range ttsFiles {
			ttsName := strings.TrimSuffix(filepath.Base(tts), filepath.Ext(tts))
			out := filepath.Join(outputDir, ttsName+"_"+bgName+".mp3")
			if err := mix(tts, bg, out, bgmVolume, ttsVolume, delayMs, duration, fadeOut); err != nil {
				return fmt.Errorf("%s: %w", out, err)
			}
			fmt.Printf("  ✓ %s\n", filepath.Base(out))
		}
	}

	fmt.Fprintf(os.Stderr, "\nDone. %d file(s) in '%s/'\n", total, outputDir)
	return nil
}

// ── main ──────────────────────────────────────────────────────────────────────

func main() {
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "init":
			cmdInit(os.Args[2:])
			return
		case "setup":
			cmdSetup(os.Args[2:])
			return
		case "tts":
			cmdTTS(os.Args[2:])
			return
		case "reset":
			cmdReset(os.Args[2:])
			return
		case "clean":
			cmdClean(os.Args[2:])
			return
		case "doctor", "--doctor":
			fmt.Printf("astra-carplay-music %s — doctor\n\n", version)
			doctor()
			return
		case "help", "--help", "-h":
			printHelp()
			return
		case "version", "--version":
			fmt.Printf("astra-carplay-music %s\n", version)
			return
		default:
			if !strings.HasPrefix(os.Args[1], "-") {
				fmt.Fprintf(os.Stderr, "Error: unknown subcommand '%s'\n\n", os.Args[1])
				fmt.Fprintf(os.Stderr, "Run 'astra-carplay-music --help' for usage.\n")
				os.Exit(2)
			}
		}
	}

	bgmVolume   := flag.Float64("bgm-volume", -3, "Background music volume in dB (default: -3)")
	ttsVolume   := flag.Float64("tts-volume", 0, "TTS voice volume in dB (default: 0)")
	delay       := flag.Float64("delay", 0.5, "Seconds of background music before TTS starts (default: 0.5)")
	duration    := flag.Float64("duration", 0, "Trim output to this duration in seconds (default: full length)")
	fadeOut     := flag.Float64("fade-out", 0, "Fade out duration in seconds at end (default: none)")
	showVersion := flag.Bool("version", false, "Show version")
	showDoctor  := flag.Bool("doctor", false, "Check required dependencies")

	flag.Usage = printHelp
	flag.Parse()

	if *showVersion {
		fmt.Printf("astra-carplay-music %s\n", version)
		os.Exit(0)
	}
	if *showDoctor {
		fmt.Printf("astra-carplay-music %s — doctor\n\n", version)
		doctor()
		os.Exit(0)
	}

	if err := runMix(*bgmVolume, *ttsVolume, int(*delay*1000), *duration, *fadeOut); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}
}

func printHelp() {
	fmt.Fprintf(os.Stderr, "astra-carplay-music %s\n", version)
	fmt.Fprintf(os.Stderr, "Mix TTS audio × background music for CarPlay. Output saved to %s/\n\n", outputDir)

	fmt.Fprintf(os.Stderr, "Getting started (first time):\n")
	fmt.Fprintf(os.Stderr, "  1. astra-carplay-music init                          # create folder structure\n")
	fmt.Fprintf(os.Stderr, "  2. astra-carplay-music setup --api-key <key>         # set ElevenLabs API key\n")
	fmt.Fprintf(os.Stderr, "  3. Drop background music files into %s/\n", bgmDir)
	fmt.Fprintf(os.Stderr, "  4. Edit scripts.txt — one line per TTS clip\n")
	fmt.Fprintf(os.Stderr, "  5. astra-carplay-music tts --file scripts.txt        # generate TTS\n")
	fmt.Fprintf(os.Stderr, "  6. astra-carplay-music --duration 7 --fade-out 1.5  # mix output\n\n")

	fmt.Fprintf(os.Stderr, "Subcommands:\n")
	fmt.Fprintf(os.Stderr, "  init       Create folder structure + sample scripts.txt (first run)\n")
	fmt.Fprintf(os.Stderr, "  setup      Set ElevenLabs API key and Voice ID\n")
	fmt.Fprintf(os.Stderr, "  tts        Generate TTS audio via ElevenLabs API\n")
	fmt.Fprintf(os.Stderr, "  reset      Delete TTS + output files, keep background music\n")
	fmt.Fprintf(os.Stderr, "  clean      Delete audio files from specific directories\n")
	fmt.Fprintf(os.Stderr, "  --doctor   Check dependencies (ffmpeg)\n\n")

	fmt.Fprintf(os.Stderr, "Mix options (no subcommand needed):\n")
	fmt.Fprintf(os.Stderr, "  --bgm-volume float   Background music volume, dB        (default: -3)\n")
	fmt.Fprintf(os.Stderr, "  --tts-volume float   TTS voice volume, dB               (default: 0)\n")
	fmt.Fprintf(os.Stderr, "  --delay float        Seconds of BG music before TTS     (default: 0.5)\n")
	fmt.Fprintf(os.Stderr, "  --duration float     Output length in seconds           (default: full)\n")
	fmt.Fprintf(os.Stderr, "  --fade-out float     Fade out duration in seconds       (default: none)\n")
	fmt.Fprintf(os.Stderr, "  --version            Show version\n\n")

	fmt.Fprintf(os.Stderr, "Directories:\n")
	fmt.Fprintf(os.Stderr, "  %-28s TTS audio files (.mp3/.wav/.m4a)\n", ttsDir+"/")
	fmt.Fprintf(os.Stderr, "  %-28s Background music (.mp3/.wav/.m4a)\n", bgmDir+"/")
	fmt.Fprintf(os.Stderr, "  %-28s Mixed output files\n\n", outputDir+"/")

	fmt.Fprintf(os.Stderr, "For subcommand help: astra-carplay-music <subcommand> --help\n")
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
